# Generated by Django 4.0.4 on 2022-04-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_delete_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
